service: expenses-tracker

package: 
  individually: true

provider:
  name: aws
  lambdaHashingVersion: 20201221
  region: eu-central-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - "Fn::Join":
            - ""
            - - "Fn::GetAtt": [ DynamoDB, Arn ]
              - "*"
  environment:
    TABLE_NAME: ${self:custom.tableName}

custom:
  tableName: expenses

functions:
  fetchAllExpenses:
    runtime: provided.al2023
    handler: fetchAllExpenses
    events:
      - http:
          path: expenses-tracker
          method: GET
          cors: true
    package: 
      artifact: bin/fetchAllExpenses.zip
  getExpenseStatistics:
    runtime: provided.al2023
    handler: getExpenseStatistics
    events:
      - http:
          path: expenses-tracker/statistics
          method: GET
          cors: true
    package: 
      artifact: bin/getExpenseStatistics.zip
  addExpense:
    runtime: provided.al2023
    handler: addExpense
    events:
      - http:
          path: expenses-tracker
          method: POST
          cors: true
    package: 
      artifact: bin/addExpense.zip

resources:
  Resources:
    DynamoDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

